# TODO: re-enable Metric/AbcSize, Metrics/CyclomaticComplexity, and Metrics/PerceivedComplexity
AllCops:
  DisplayCopNames: true
  Exclude:
    - .bundle/*
    - bin/*
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/**/*_spec.rb"
Metrics/ClassLength:
  Max: 300
Metrics/LineLength:
  Max: 280
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 120
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
# enable Naming/PredicateName as part of ruby_aem v2
Naming/PredicateName:
  Enabled: false
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/BlockDelimiters:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
