---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.SHINEOPENSOURCE_GITHUB_TOKEN }}
      - uses: cliffano/command-docker-action@v2.1.0
        with:
          command: 'make ci'
          image: shinesolutions/aem-platform-buildenv:4.1.0
          shell: bash
